name: werewolf_game
description: Game sosial deduksi Werewolf dengan Flutter dan PocketBase.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  intl: ^0.18.1
  google_fonts: ^5.1.0
  pocketbase: ^0.22.0
  shared_preferences: ^2.2.0
  flutter_svg: ^2.0.7
  audioplayers: ^5.1.0
  flutter_animate: ^4.2.0
  connectivity_plus: ^4.0.2
  cached_network_image: ^3.2.3
  flutter_chat_ui: ^1.6.9
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2 
  firebase_database: ^10.3.8 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app_icon.png"